spring:
  application:
    name: SprinBootSecurity
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: tkd
    password: tkd
    driver-class-name: org.h2.Driver
server:
  port: 8088
endpoints:
  health:
    enabled: true
management:
  security:
    enabled: false

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO